create database weblutra;
use weblutra;

CREATE TABLE ROLE
(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ROLE_NAME VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE USER
(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ROLER_ID INT NOT NULL,
    FullNAME VARCHAR(155) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    TELEPHONE VARCHAR(15) NOT NULL UNIQUE,
    ADDRESS TEXT,
    Image VARCHAR(500),
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CREATOR TEXT,
    MODIFIED TIMESTAMP,
    MODIFIER TEXT,
    STATUS INT DEFAULT 0,
    FOREIGN KEY(ROLER_ID) REFERENCES ROLE(ID)
);
CREATE TABLE CATEGORY
(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    PAREN_ID INT NOT NULL,
    NAMECATE TEXT NOT NULL,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CREATOR TEXT,
    MODIFIED TIMESTAMP ,
    MODIFIER TEXT
);
CREATE TABLE PRODUCT
(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    CATEGORY_ID INT NOT NULL,
    COLOR VARCHAR(500),
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    CODE VARCHAR(500),
    PRICE REAL NOT NULL,
    QUANTITY INT ,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CREATOR TEXT,
    MODIFIED TIMESTAMP, /*tg sửa */
    MODIFIER TEXT, /* ng sửa */
    STATUS INT DEFAULT 0,
    FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORY(ID)
);
CREATE TABLE SIZE
(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    SIZE TEXT NOT NULL,
    QUANTITY INT NOT NULL,
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID)
);
CREATE TABLE MEDIA
(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    URL TEXT NOT NULL,
    DESCRIPTION INT NOT NULL,
    TYPE VARCHAR(500),
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID)
);
CREATE TABLE VOUCHER
(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    NAME TEXT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    DESCRIPTION TEXT,
    QUANTITY INT NOT NULL,
    EFFECT_FROM TIMESTAMP,
    EFFECT_UNTIL TIMESTAMP,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CREATOR TEXT,
    MODIFIED TIMESTAMP,
    MODIFIER TEXT,
    VALUE INT NOT NULL,
    TYPE INT NOT NULL,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);
CREATE TABLE ORDERS
(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    VOUCHER_ID INT,
    CODE VARCHAR(255) NOT NULL UNIQUE,
    SIZE_ID INT NOT NULL,
    USER_ID INT,
    QUANTITY INT,
    PRICE REAL,
    NAME_RECIPIENT VARCHAR(500),
    TELEPHONE VARCHAR(15),
    ADDRESS VARCHAR(255),
    EFFECT_FROM TIMESTAMP,
    EFFECT_UNTIL TIMESTAMP,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CREATOR TEXT,
    MODIFIED TIMESTAMP,
    MODIFIER TEXT,
    STATUS INT DEFAULT 1,
    FOREIGN KEY(VOUCHER_ID) REFERENCES VOUCHER(ID),
    FOREIGN KEY(USER_ID) REFERENCES USER(ID),
    FOREIGN KEY(SIZE_ID) REFERENCES SIZE(ID)
);
CREATE TABLE BILL
(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    USER_ID INT NOT NULL,
    CODE VARCHAR(255) NOT NULL UNIQUE,
    NAME_RECIPIENT VARCHAR(500),
    TELEPHONE VARCHAR(15),
    ADDRESS VARCHAR(255),
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CREATOR TEXT,
    MODIFIED TIMESTAMP,
    MODIFIER TEXT,
    FOREIGN KEY(USER_ID) REFERENCES USER(ID)
);
CREATE TABLE BILL_DETAIL
(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    BILL_ID INT NOT NULL,
    SIZE_ID INT NOT NULL,
    VOUCHER_ID INT ,
    QUANTITY INT,
    PRICE REAL,
    FOREIGN KEY(SIZE_ID) REFERENCES SIZE(ID),
    FOREIGN KEY(VOUCHER_ID) REFERENCES VOUCHER(ID)
);
CREATE TABLE CART
(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    USER_ID INT NOT NULL,
    SIZE_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    CREATOR TEXT,
    MODIFIED TIMESTAMP,
    MODIFIER TEXT,
    STATUS INT DEFAULT 1,
    FOREIGN KEY(USER_ID) REFERENCES USER(ID),
    FOREIGN KEY(SIZE_ID) REFERENCES SIZE(ID)
);
CREATE TABLE COMMENT
(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    USER_ID INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PARENT_ID INT ,
    CONTENT TEXT,
    CREATED TIMESTAMP,
    CREATOR TEXT,
    STATUS INT DEFAULT 1,
    FOREIGN KEY(USER_ID) REFERENCES USER(ID),
    FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(ID),
    FOREIGN KEY(PARENT_ID) REFERENCES COMMENT(ID)
);

